Create swap button functionality
aronvaupel/SwapIt-Capstone pull request #64
Opened 2021-09-24 09:12 UTC by aronvaupel

Create swap button function and all necessary preconditions (hopefully).

2021-09-24 12:15 UTC, marwinburesch reviewed
Gogogogo
- Your delete methods don't necessarily need a whole proposal to work, [an id would suffice](https://docs.mongodb.com/manual/reference/method/db.collection.deleteOne/)

2021-09-24 12:15 UTC, marwinburesch commented on src/app/pages/MainPage/MainPage.tsx
> +            'Content-type': 'applicatio/json',
```suggestion
            'Content-type': 'application/json',
```

2021-09-24 12:15 UTC, marwinburesch commented on src/app/pages/MainPage/MainPage.tsx
> +  async function handleClick() {
Almost everything here should happen in your backend

2021-09-24 12:21 UTC, aronvaupel commented on src/app/pages/MainPage/MainPage.tsx
> +            'Content-type': 'applicatio/json',
thx

2021-09-27 14:40 UTC, phlgr requested changes

2021-09-27 14:40 UTC, phlgr commented on src/server.ts
> +        proposal.items.toString() === newProposal.items.toString()
This seems highly complicated. Why don't you have a prop/key for each user?

2021-09-27 14:40 UTC, phlgr commented on src/server.ts
> +    if (matchingProposal !== undefined) {
```suggestion
    if (matchingProposal) {
```

2021-09-27 14:40 UTC, phlgr commented on src/server.ts
> +      await deleteProposal(newProposal);
Why not just the id?

2021-09-27 14:40 UTC, phlgr commented on src/server.ts
> +  const { match } = req.body;
Why are you destructuring here?

2021-09-27 14:40 UTC, phlgr commented on src/server.ts
> +app.delete('/api/matches', async (req, res) => {
```suggestion
app.delete('/api/matches/:id', async (req, res) => {
```
The id is sufficient to delete a match

2021-09-27 14:40 UTC, phlgr commented on src/server.ts
> +  const { proposal } = req.body;
Why are you destructuring here?

2021-09-27 14:40 UTC, phlgr commented on src/server.ts
> +  const { users, items } = req.body;
Why are you destructuring here?

2021-09-27 14:40 UTC, phlgr commented on src/server.ts
> +    const result = await getProposal(users, items);
You should retrieve a single document from a collection based on one unique identifier, like the `_id`

2021-09-27 14:40 UTC, phlgr commented on src/utils/items.ts
> +  await items.updateOne({ _id: id }, { $set: { item } });
You could upsert here

2021-09-27 14:40 UTC, phlgr commented on src/utils/matches.ts
> +  await matches.insertOne(match);
You should return the newly inserted document

2021-09-27 14:40 UTC, phlgr commented on src/utils/matches.ts
> +  await matches.deleteOne(match);
You should return if it got deleted or throw an error if not

2021-09-27 14:40 UTC, phlgr commented on src/utils/proposals.ts
> +  await proposals.insertOne(proposal);
You should return the newly inserted document

2021-09-27 14:40 UTC, phlgr commented on src/utils/proposals.ts
> +  await proposals.deleteOne(proposal);
You should implement error handling here

2021-09-27 14:40 UTC, phlgr commented on src/utils/proposals.ts
> +  const proposal = await proposals.findOne({ users, items });
You should find the Proposal based on the `_id`

2021-09-27 14:40 UTC, phlgr commented on src/utils/types.ts
> +  creator: ObjectId;
Why is a creator necessary?
I would highly recommend splitting the arrays into two separate key/value pairs each.

2021-09-27 14:40 UTC, phlgr commented on src/utils/types.ts
> +  items: ObjectId[];
The above also applies here

2021-09-27 16:34 UTC, aronvaupel commented on src/app/pages/MainPage/MainPage.tsx
> +      users: [ownItems[0].ownerId, otherItems[0].ownerId].sort(),
The selected Item in the carousel has index position 0

2021-09-27 16:53 UTC, aronvaupel commented on src/utils/types.ts
> +  items: ObjectId[];
Why?

2021-09-27 16:53 UTC, aronvaupel commented on src/utils/types.ts
> +  creator: ObjectId;
Interesting. Why?

2021-09-27 16:54 UTC, aronvaupel commented on src/utils/items.ts
> +  await items.updateOne({ _id: id }, { $set: { item } });
The main problem here, is that the document in the database does not update at all.

2021-09-27 17:00 UTC, aronvaupel commented on src/app/pages/MainPage/MainPage.tsx
> +      users: [ownItems[0].ownerId, otherItems[0].ownerId].sort(),
I left away any sorting parameters, because if they are all sorted in the same way, that will be sufficient for later comparison, right?

2021-09-27 17:01 UTC, aronvaupel commented on src/app/pages/MainPage/MainPage.tsx
> +    fetchOtherItems();
Maybe. Since my capabilities and my time are limited I will live with the current solution.

2021-09-27 17:09 UTC, aronvaupel commented on src/utils/types.ts
> +  creator: ObjectId;
was an experiment, removed it long ago. The pull request was from 10a.m.

2021-09-28 07:51 UTC, aronvaupel commented on src/server.ts
> +        proposal.items.toString() === newProposal.items.toString()
Because it is two users, and only one is known in advance.

2021-09-28 14:17 UTC, marwinburesch commented on src/utils/types.ts
> +  creator: ObjectId;
If you have users and items as individual properties, you can always be sure to get the one you need. How can you be sure which index is whose `id`?

2021-09-29 10:17 UTC, marwinburesch commented on src/app/pages/MainPage/MainPage.tsx
> +
Why don't you use a state for this? This is confusing

2021-09-30 10:26 UTC, merged